[project]
name = "odoo-addons-oca-vertical-association"
version = "19.0.20260805.0"
dependencies = [
    "odoo-addon-contract_membership_delegated_partner==19.0.*",
    "odoo-addon-membership==19.0.*",
    "odoo-addon-membership_delegated_partner==19.0.*",
    "odoo-addon-membership_variable_period==19.0.*",
    "odoo-addon-website_membership==19.0.*",
    "odoo-addon-website_membership_gamification==19.0.*",
    "odoo-addon-website_membership_random_order==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
