[project]
name = "odoo-addons-oca-vertical-association"
version = "18.0.20251112.0"
dependencies = [
    "odoo-addon-contract_membership_delegated_partner==18.0.*",
    "odoo-addon-membership_delegated_partner==18.0.*",
    "odoo-addon-membership_extension==18.0.*",
    "odoo-addon-membership_initial_fee==18.0.*",
    "odoo-addon-membership_prorate==18.0.*",
    "odoo-addon-membership_prorate_variable_period==18.0.*",
    "odoo-addon-membership_variable_period==18.0.*",
    "odoo-addon-membership_withdrawal==18.0.*",
    "odoo-addon-website_membership_gamification==18.0.*",
    "odoo-addon-website_membership_random_order==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
